CREATE TABLE STUDENT (
stu_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
stu_rut INT NOT NULL,
stu_dv VARCHAR(1) NOT NULL,
stu_name01 VARCHAR(16) NOT NULL,
stu_name02 VARCHAR(16),
stu_surname01 VARCHAR(16) NOT NULL,
stu_surname02 VARCHAR(16) NOT NULL,
grade_id INT REFERENCES GRADE(grade_id) NOT NULL
)

CREATE TABLE GRADE (
grade_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
grade_number INT NOT NULL,
grade_letter VARCHAR(1) NOT NULL
)